config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  get 'render/index'
  get "up" => "rails/health#show", as: :rails_health_check

  #Rutas get
  get 'posts/index'
  get 'posts/create'
  get 'posts/new'

  #Rutas Post
  post "posts" => "posts#create"
  
  root "render#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < ApplicationRecord
    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :brand, :name, presence: true, length: {in: 2..10 } 
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
    validates :email, uniqueness: {case_sensitive: false} 
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all #0 , 1 ...n
  end

  def new
    #Captura los datos enviados en el formulario
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)

    if @post.save
      redirect_to posts_index_path
    else
      render :new
    end
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Post totales: <%= @posts.count %>
</p>

<%= form_with model: @post, method: :post do |form| %>
  <div class="col-4 my-3">
      <div>
          <%= form.label :title, "Post Title" , class: "form-label" %>
              <%= form.text_field :title, class: "form-control" %>
      </div>
      <br>
      <div>
          <%= form.label :content, "Post Content" , class: "form-label" %>
          <%= form.text_field :content, class: "form-control" %>
      </div>
      <br>
      <div>
          <%= form.submit "Submit" , class: "btn btn-primary" %>
      </div>
  </div>
<% end %>

<%= link_to "Agregar nuevo Post", posts_new_path %>

<table class="table">
<thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Content</th>
    <th scope="col">Actions</th>
  </tr>
</thead>
<tbody>
<% @posts.each do |post| %>

      <tr>
        <th scope="row">
          <%= post.id %>
        </th>
        <td>
          <%= post.title %>
        </td>
        <td>
          <%= post.content %>
        </td>
        <td></td>
      </tr>
  <% end%>
      </tbody>
  </table>

app/views/posts/new.html.erb
<%= form_with model: @post, method: :post do |form| %>
    <div class="col-4 my-3">
        <div>
            <%= form.label :title, "Post Title" , class: "form-label" %>
                <%= form.text_field :title, class: "form-control" %>
        </div>
        <br>
        <div>
            <%= form.label :content, "Post Content" , class: "form-label" %>
            <%= form.text_field :content, class: "form-control" %>
        </div>
        <br>
        <div>
            <%= form.submit "Submit" , class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/render/index.html.erb
<main class="container">
    <div class="row text-center justify-content-center">
        <div class="col">
            <h1 class="display-4">Hello World!</h1>
        </div>
    </div>
</main>